var config = {};

config.admin = {};
config.admin.email = 'contact@trendingnow.io';

config.commonSenseEdge = 150; // do not let pass hashtags with less that that amount of mentions
config.zScorePos = 1.95; //2.58; // 1.95;
config.zScoreNeg = -1.95; //2.58; //-1.95
config.zScoreEmail = 3; // idunnolol

config.mailgun = {apiKey: 'key-8e0f686bcd2d829f37db872bf81f6a06', domain: 'sandbox9bffcf33276b457ca27bc8d1fea59cc4.mailgun.org'};
config.mailgun.mailingList = 'trending@sandbox9bffcf33276b457ca27bc8d1fea59cc4.mailgun.org';

config.twitter = {
    consumer_key: 'tqMsxyNJ57fsBU5kfhNGCmOvD',
    consumer_secret: 'H1YkMj0dDtLh95bD2pwk02sJLupqbN3YzkyF5jO21KuZl03UXu',
    access_token: '23313645-O6qC4ZPisg4Eswke7K2DXoer4KZgnhPnq6pebzInH',
    access_token_secret: 'DREtpcSvQpnz080qtHKZWXpRDFfbvRxdAIzBBIgqL3hxN',
    timeout_ms: 60 * 1000,
};

config.mongodb = {
    url: 'mongodb://127.0.0.1:27017/twitter_feed'
};

config.forbiddenWords = [
'#sale', 'sale', 'deals', '#deals',
'hot','amateur','anal','sex','cum','girls','#cam','wet','#hardcore','#amateursex','#amateur','wife','dick','mirrorphotos','#porngif','#analvideos','#analtube','fuck',
'#nowplaying', 'adult', '#adult', 'teen', '#teen', '#follow', '#hot', '#giveaway', 'giveaway', '#androidgames', '#teamfollowback', '#retweet', '#f4f', '#twitter', '#cumshot', '#blowjob', '#sex', '#porn', '#fuck', '#ass', '#pussy',
'#sexy', '#xxx', '#naked', '#horny', '#whore', '#boobs', '#tits', '#anal', '#deepthroat',
'amp', 'are', 'more', 'via', 'its', 'http', 'https', 'is', 'rt',
'the',
'of',
'and',
'to',
'a',
'in',
'for',
'is',
'on',
'that',
'by',
'this',
'with',
'i',
'you',
'it',
'not',
'or',
'be',
'are',
'from',
'at',
'as',
'your',
'all',
'have',
'new',
'more',
'an',
'was',
'we',
'will',
'home',
'can',
'us',
'about',
'if',
'page',
'my',
'has',
'search',
'free',
'but',
'our',
'one',
'other',
'do',
'no',
'information',
'time',
'they',
'site',
'he',
'up',
'may',
'what',
'which',
'their',
'news',
'out',
'use',
'any',
'there',
'see',
'only',
'so',
'his',
'when',
'contact',
'here',
'business',
'who',
'web',
'also',
'now',
'help',
'get',
'pm',
'view',
'online',
'c',
'e',
'first',
'am',
'been',
'would',
'how',
'were',
'me',
's',
'services',
'some',
'these',
'click',
'its',
'like',
'service',
'x',
'than',
'find',];

module.exports = config;